backend:
  name: git-gateway
  branch: main # O branch que você está usando no GitHub

media_folder: "static/images/uploads" # Local onde as imagens serão armazenadas
public_folder: "/images/uploads"

collections:
  - name: "posts" # Nome da coleção
    label: "Posts" # Rótulo que aparecerá no CMS
    folder: "content/posts" # Pasta onde os arquivos .md estão localizados
    create: true # Permitir que novos posts sejam criados
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Publicar", name: "date", widget: "datetime" }
      - { label: "Texto", name: "body", widget: "markdown" }
